### ISSUE TITLE
SDL example crahses & SFX pitch issues

### ISSUE THREAD

**Issue by ColleagueRiley** [Daivuk/PureDOOM#21] opened 2024-04-21 16:34 UTC
While working on my projects that are using PureDOOM I noticed that there was an issue with the audio pitch. I was not sure if this was an issue with RGFW, Miniaudio or PureDOOM, so I decided to test the SDL example.

When I tried to test the SDL example I noticed,
1) The CMake script doesn't compile the SDL example. 
2) When I compiled the sdl example by hand (on linux, and on windows, via mingw) it seg faults.

**Comment by ColleagueRiley** [comment] 2024-04-21 17:00
Update: 

The pitch-shifting part is just a normal part of the engine. Newer versions of DOOM seem to remove this feature. Maybe it should be made optional?

**Comment by Daivuk** [comment] 2024-04-21 17:41
The issue is not PureDOOM because the audio buffer is generated properly on linux. I have unit tests that runs on Linux. Tested on both Windows and Mac.

I don't have a local Linux machine to debug SDL CMake sorry. If you find a fix don't hesitate to propose a PR. But make sure you're installing SDL properly.

**Comment by ColleagueRiley** [comment] 2024-04-21 17:55
This issue (the seg fault and compiling not working) happens to me both with Windows (using MinGW) and Linux. 

The audio issue is not an issue, as I said. It's just a feature in the DOOM engine that modern source ports have removed.

**Comment by ColleagueRiley** [comment] 2024-04-21 17:57
I don't know if your unit test would catch the seg fault if it's an issue with the SDL example.

**Comment by Daivuk** [comment] 2024-04-21 18:03
I do not seg fault on neither windows or mac. Are you building it with the SDL submodule?

**Comment by ColleagueRiley** [comment] 2024-04-21 18:54
> I do not seg fault on neither windows or mac. Are you building it with the SDL submodule?

The submodule is not included when I `git clone` so I must use my copy.

**Comment by ColleagueRiley** [comment] 2024-04-21 19:32
Okay, I cloned SDL into where it's supposed to be. Even if this does work it's ridiculous that you have to go through all this trouble with cmake and then compile a big library like SDL. 

Update: SDL gave me an error and now I'll have to restart the process to get it working.
This is happening on Windows 10 with MinGW.

**Comment by Daivuk** [comment] 2024-04-21 19:52
You have to clone submodules like this:
```git submodule update --init --recursive```
This is not an issue about this repository or code base, closing.

**Closed by Daivuk** 2024-04-21 19:52 UTC

**Comment by ColleagueRiley** [comment] 2024-04-21 21:04
> You have to clone submodules like this: `git submodule update --init --recursive` This is not an issue about this repository or code base, closing.

Well no, I did it that way and got the same results.
